# Generated by Django 4.2.15 on 2024-09-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_post_created_time_remove_post_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': "Post's"},
        ),
    ]
