# Generated by Django 4.2.15 on 2024-09-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='updated_time',
        ),
    ]
