# Generated by Django 4.2.13 on 2024-09-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contact_created_at_contact_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
