# Generated by Django 4.2.13 on 2024-09-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_nationality_post_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, default='all', null=True, to='blog.category'),
        ),
    ]
