# Generated by Django 4.2.13 on 2024-09-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
