# Generated by Django 4.2.13 on 2024-09-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
