# Generated by Django 4.2.13 on 2024-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
